### ISSUE TITLE
Compatibility with Firefox 79.0.5 for Android ?

### ISSUE THREAD

**Issue by Auze** [mozilla/video-bg-play#26] opened 2020-09-04 09:38 UTC
Hello, 

I recently updated Firefox to version 79.0.5 for Android 9. 
This version does not allow user to browse all the extension, only a selected list.

Is a compatibility with this new version planned ? 

Thank you !

**Comment by buttercookie42** [comment] 2020-09-04 17:24
Duplicate of #20.

(The add-on itself is compatible, the problem is that Mozilla is currently limiting what add-ons can be installed in the new browser version, so any complaints about that need to go to them.
The good news is that since yesterday or so the add-on *is* available on Nightly, although on the other hand due to a [separate Firefox bug](https://github.com/mozilla-mobile/fenix/issues/9691) it's only of limited value until that one gets fixed as well.
Beta and Release users will probably (and unfortunately) have to wait a little longer – even if that Firefox bug was fixed tomorrow in Nightly it'd take some time until it's fixed in Beta or especially the Release version as well.)

**Closed by buttercookie42** 2020-09-04 17:24 UTC
Labels: duplicate
