### ISSUE TITLE
Autoplay doesn't work in background on Android (Youtube)

### ISSUE THREAD

**Issue by CreamyCookie** [mozilla/video-bg-play#17] opened 2019-05-16 15:47 UTC

**Comment by buttercookie42** [comment] 2019-05-16 18:51
Duplicate of #16.

**Comment by buttercookie42** [comment] 2019-05-16 21:13
Okay, leaving this as a separate issue for Autoplay specifically, although I don't see anything strange either - I tried a video outside of a playlist, left autoplay enabled and it then continued with the next video while in background just fine.

**Comment by CreamyCookie** [comment] 2019-05-16 21:31
Hmm.. no idea if this can have an effect, but was your screen off? (Should have mentioned that in the original post, but I only now remembered.)

**Comment by buttercookie42** [comment] 2019-05-16 22:01
No, it wasn't. I can try it again some time, although if that really turns out to matter, there might be not much I can do, because if the tab and/or Firefox is in the background anyway, screen on/off should only affect things between Android and Firefox, of which I have no control over from an add-on.

**Comment by buttercookie42** [comment] 2019-05-23 18:01
I did try it with the screen off, but on my phone there's no difference.
To clarify, you are saying that there are clear and reproducible differences in behaviour depending on whether
- the Youtube tab is in the background, but Firefox itself is the foreground app
- Firefox itself is in the background, but the screen is on, or
- the screen is off?

**Comment by CreamyCookie** [comment] 2019-05-23 19:38
Okay, this is what I just did to reproduce it:

1. Open a video (and skip to 10 seconds before end)
2. Open another tab, search sth. (actually using the tab might not matter)
3. Go to your Android home screen
4. Turn the screen off.

When I switch back to the tab, it either stops completely.. or the autoplay progress thing continues and then the next video loads..

That said, it only happened 2 out of 5 times, so it seems very inconsistent. (And some of the steps above are probably unnecessary.)

**Comment by klesun** [comment] 2021-01-07 23:10
Not sure it's same issue as OP had, but nowadays youtube autoplay does not seem to work when screen is either turned off or when in background (on my galaxy s10e device at least with firefox v84.1.2)

Neither recommended video autoplay, nor playlist autoplay works for me. Not 3 out of 7 times, but never.

**Comment by buttercookie42** [comment] 2021-01-08 10:59
Hmm, I've done a test run, and with the old Firefox (68), there are now noticeable pauses inbetween tracks when in background (which get *veeery* long when the screen is off as well) which I don't remember happening before, so something did change on Youtube's part at some point.

With a current Firefox Nightly from yesterday (2021-01-07), though, I'm not seeing any problems – the playlist plays fine and switches tracks successfully no matter whether only the tab or Firefox as a whole is in the background, or even when the screen is off.

**Comment by buttercookie42** [comment] 2021-04-22 22:19
Currently seems to be working reasonably well again even in Firefox 68 and even with the screen off, plus whatever Firefox and/or Android are up to while in background isn't really within my control.

**Closed by buttercookie42** 2021-04-22 22:19 UTC
