### ISSUE TITLE
Please add a PIP fix for YouTube. 

### ISSUE THREAD

**Issue by Ksanbah** [mozilla/video-bg-play#38] opened 2023-05-15 00:44 UTC
The Picture-in-picture mode does not work for the website, and I honestly don't know who could fix it better than you guys. This add-on is a fix for video background audio, but maybe you could add a PIP fix for YouTube. Please consider. Thank you :)

**Comment by claudiu64** [comment] 2023-05-29 22:57
@Ksanbah If you have Firefox Mobile Browser, the problem is known and will be fixed: https://bugzilla.mozilla.org/show_bug.cgi?id=1827583

**Comment by Ksanbah** [comment] 2023-05-30 01:42
Noted Tk U.

**Closed** 2023-05-30 07:18 UTC
